# Generated by Django 5.0.6 on 2026-05-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('about', models.TextField(blank=True, verbose_name='Описание')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Требуемый опыт (лет)')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ЗП от')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ЗП до')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('internship', 'Стажировка'), ('contract', 'Договор'), ('freelance', 'Фриланс')], default='full_time', max_length=15, verbose_name='Тип занятости')),
                ('schedule', models.CharField(choices=[('five_days', 'Пятидневка'), ('shift', 'Сменный'), ('flexible', 'Гибкий'), ('remote', 'Удалённый')], default='five_days', max_length=15, verbose_name='График')),
                ('work_format', models.CharField(choices=[('office', 'Офис'), ('remote', 'Удалённо'), ('hybrid', 'Гибрид')], default='office', max_length=10, verbose_name='Формат работы')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('paused', 'Приостановлена'), ('closed', 'Закрыта')], default='active', max_length=10, verbose_name='Статус')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Актуальна до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('viewed', 'Просмотрено'), ('accepted', 'Приглашение'), ('rejected', 'Отказ')], default='pending', max_length=10, verbose_name='Статус')),
                ('employer_comment', models.TextField(blank=True, verbose_name='Комментарий работодателя')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма к оплате')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('vacancy', 'resume'), name='uq_application'),
        ),
    ]
