# Generated by Django 5.0.6 on 2026-05-26 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ИНН')),
                ('industry', models.CharField(blank=True, max_length=150, verbose_name='Сфера деятельности')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип')),
                ('about', models.TextField(blank=True, verbose_name='Об организации')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
                'db_table': 'employers',
            },
        ),
    ]
