# Generated by Django 5.0.6 on 2026-05-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('status', models.CharField(choices=[('actively_looking', 'Активно ищу работу'), ('open_to_offers', 'Рассматриваю предложения'), ('not_looking', 'Не ищу работу')], default='actively_looking', max_length=20, verbose_name='Статус поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='ApplicantPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=20, verbose_name='Серия')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('scan', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Скан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
                'db_table': 'applicant_passports',
            },
        ),
        migrations.CreateModel(
            name='ApplicantWorkBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('scan', models.FileField(blank=True, null=True, upload_to='workbooks/', verbose_name='Скан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_book', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Трудовая книжка',
                'verbose_name_plural': 'Трудовые книжки',
                'db_table': 'applicant_work_books',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Желаемая должность')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('salary_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Желаемая ЗП')),
                ('education', models.CharField(blank=True, choices=[('no_education', 'Без образования'), ('secondary', 'Среднее'), ('vocational', 'Среднее специальное'), ('incomplete_higher', 'Неполное высшее'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат/доктор наук')], max_length=20, verbose_name='Образование')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Резюме PDF')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('hidden', 'Скрытое'), ('archived', 'В архиве')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
